// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateOrUpdateSetting(arg1, arg2) {
  return window['go']['backend']['Backend']['CreateOrUpdateSetting'](arg1, arg2);
}

export function GetAllSettings() {
  return window['go']['backend']['Backend']['GetAllSettings']();
}
