// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CreateOrUpdateSetting(arg1:string,arg2:string):Promise<string>;

export function GetAllSettings():Promise<Array<backend.Setting>>;
